# AUTOGENERATED! DO NOT EDIT! File to edit: 50a_web_demo.ipynb (unless otherwise specified).

__all__ = ['bp', 'get_single_patient_medication_bundle', 'index']

# Cell
from ..per_patient import *

from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import send_from_directory
from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename
import tempfile,time,json
from pathlib import Path

bp = Blueprint("demo", __name__)

# Cell
def get_single_patient_medication_bundle(api_base, subject):
    bundle = create_single_patient_medication_bundle(api_base, subject)
    bundle = handle_entry_search(bundle)
    bundle = filter_bundle(bundle, medication_status_filter)
    bundle = filter_bundle(bundle, do_not_perform_filter)
    return bundle

# Cell
@bp.route("/", methods=("GET", "POST"))
def index():
    """Show all the index page."""
    medication_bundle = ''
    if request.method == "POST":
        api_base = request.form["api_base"]
        subject = request.form["subject"]
        print(api_base, subject)
        error = None

        if not api_base:
            error = "api_base is required."
        if not subject:
            error = "subject is required"

        if error is not None:
            flash(error)
        else:
            medication_bundle = get_single_patient_medication_bundle(api_base, subject)
            medication_bundle = json.dumps(medication_bundle, indent=2)

    return render_template("index.html", medication_bundle=medication_bundle)