# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_bundle_as_raw_json": "00_core.ipynb",
         "get_next_bundle_as_raw_json": "00_core.ipynb",
         "timestamp_now": "00_core.ipynb",
         "new_bundle": "00_core.ipynb",
         "extract_references_from_resource": "00_core.ipynb",
         "extract_references": "00_core.ipynb",
         "get_by_reference": "00_core.ipynb",
         "create_single_patient_medication_bundle": "10_per_patient.ipynb",
         "save_single_patient_medication_bundle": "10_per_patient.ipynb",
         "handle_entry_search": "10_per_patient.ipynb",
         "filter_bundle": "10_per_patient.ipynb",
         "medication_status_filter": "10_per_patient.ipynb",
         "do_not_perform_filter": "10_per_patient.ipynb",
         "single_patient_medication_bundle": "30_cli.ipynb",
         "get_single_patient_medication_bundle": "50a_web_demo.ipynb",
         "create_app": "50_web_app.ipynb",
         "bp": "50a_web_demo.ipynb",
         "index": "50a_web_demo.ipynb",
         "convert_to_cdisc": "50a_web_demo.ipynb"}

modules = ["core.py",
           "per_patient.py",
           "cli.py",
           "web/app.py",
           "web/demo.py"]

doc_url = "https://pete88b.github.io/vulcan_medication_bundle/"

git_url = "https://github.com/pete88b/vulcan_medication_bundle/tree/main/"

def custom_doc_links(name): return None
