# AUTOGENERATED! DO NOT EDIT! File to edit: 30_cli.ipynb (unless otherwise specified).

__all__ = ['single_patient_medication_bundle', 'remove_non_utf8']

# Cell
from .per_patient import *
from fastcore.script import *
from pathlib import Path

# Cell
@call_parse
def single_patient_medication_bundle(
        api_base:Param('FHIR server URL',str),
        subject:Param('Patient ID',str),
        output_path:Param('Path to save bundle in',str)='data'):
    "Save a JSON Bundle containing medications for a Patient"
    bundle = create_single_patient_medication_bundle(api_base, subject)
    bundle = handle_entry_search(bundle)
    bundle = filter_bundle(bundle, medication_status_filter)
    bundle = filter_bundle(bundle, do_not_perform_filter)
    save_single_patient_medication_bundle(bundle, output_path)

# Cell
@call_parse
def remove_non_utf8(
        from_path:Param('Folder to find files in',str)='docs',
        glob_pattern:Param('Pattern to glob for',str)='*.html'):
    for file_path in Path(from_path).glob(glob_pattern):
        print('Removing non-utf8 from', file_path)
        with open(file_path, 'rb') as f: contents = f.read()
        with open(file_path, 'w') as f: f.write(contents.decode('utf-8', 'ignore'))